baseURL = "https://Replaydead.github.io/"
locale = "ja"
title = "Bleeding Frames"
theme = "hugo-theme-stack"
paginate = 10

[params]
    mainSections = ["posts"]
    defaultTheme = "dark"

[params.sidebar]
    emoji = "🎬"
    subtitle = "映画・アニメ・技術"

[params.article]
    math = false
    toc = true
    readingTime = true
    license.enabled = false

[params.colorScheme]
    toggle = true
    default = "dark"

[menu]
    [[menu.main]]
        identifier = "drama"
        name = "ドラマ"
        url = "#"
        weight = 1

    [[menu.main]]
        identifier = "bambino"
        name = "バンビ～ノ！レビュー"
        url = "/posts/bambino/"
        parent = "drama"
        weight = 1

[params.comments]
    enabled = true
    provider = "disqus"

[params.comments.disqus]
    shortname = "bleeding-frames"

    
